# site properties and page defaults
title: Xu Lab
subtitle: Dalian University of Technology
description:
header: images/ai.png
footer: images/dsRNA.jpg
header-dark: false
logo-text: true
show-title: false
show-subtitle: true

# site social media and other links
links:
  email: mxu@dlut.edu.cn
  orcid: 0000-0002-1305-0010
  google-scholar: nErn9W8AAAAJ&hl=en
  github: ittong
  # twitter: QinA2I
  # youtube: QinLiLab   

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
