- id: doi:10.1016/j.media.2025.103456
  type: paper
  description:
  image: images\citations\25mia.png
  tags:
    - Foundation models
    - Computational pathology
    - Multiple instance learning

- id: doi:10.1007/978-3-031-72378-0_9
  image: images/citations/24miccai.jpg
  tags:
    - Computational pathology
    - Multiple instance learning

- id: doi:10.1109/JBHI.2024.3485703
  image: images/citations/24jbhi.jpg


